pragma solidity ^0.8.19;

import {VersionGadget} from "src/gadgets/VersionGadget.sol";
import {AttestationGadget} from "src/gadgets/AttestationGadget.sol";
import {CensorshipResistanceGadget} from "src/gadgets/CensorshipResistanceGadget.sol";

import {PKE} from "src/crypto/encryption.sol";
import {BIP32} from "src/BIP32.sol";

import {IAndromeda} from "src/IAndromeda.sol";

// CensorshipResistanceGadget is used to enforce CR on pubkey rotation
// AttestationGadget is used to update pubkey onchain
abstract contract EncryptedInputsGadget is VersionGadget, AttestationGadget, CensorshipResistanceGadget {
    function km() internal pure virtual returns (KeyManager);

    bytes private constant input_enc_derivation_path_prefix = "m/1'";

    // Encrypt secret inputs with this key! Rotation triggers new cr epoch.
    bytes public contract_pubkey = bytes("");
    uint256 private pubkey_nonce = 0;

    /* Should only be called on local, trusted node! */
    function encrypt_contract_inputs(bytes memory plaintext, bytes32 r)
        public
        view
        returns (uint256, /* cr_epoch */ uint256, /* pubkey_nonce */ bytes memory /* ciphertext */ )
    {
        return (cr_epoch, pubkey_nonce, PKE.encrypt(contract_pubkey, r, plaintext));
    }
    /* Called internally */

    function decrypt_contract_inputs(uint256 epoch, uint256 nonce, bytes memory ciphertext)
        internal
        check_cr(epoch)
        returns (bytes memory)
    {
        return km().decrypt(_input_enc_derive_path(nonce), ciphertext);
    }

    /* Only on local node! */
    function encrypt_call(bytes4 selector, bytes memory encoded_inputs, bytes32 r)
        public
        view
        returns (uint256, /* cr_epoch */ uint256, /* pubkey_nonce */ bytes memory /* calldata */ )
    {
        return (cr_epoch, pubkey_nonce, PKE.encrypt(contract_pubkey, r, abi.encodePacked(selector, encoded_inputs)));
    }
    /* Manage encryption at the call level */

    function ecrypted_dispatch(
        uint256 epoch,
        uint256 nonce,
        bytes memory encrypted_calldata,
        bytes memory return_pubkey,
        bytes memory signature
    ) public check_cr(epoch) returns (bytes memory) {
        require(pubkey_nonce == nonce);
        require(
            PKE.verify(
                return_pubkey, keccak256(abi.encodePacked(epoch, nonce, encrypted_calldata, return_pubkey)), signature
            )
        );
        bytes memory raw_calldata = km().decrypt(_input_enc_derive_path(nonce), encrypted_calldata);
        (bool success, bytes memory data) = address(this).delegatecall(raw_calldata);
        bytes memory return_data = km().encrypt_to_pubkey(return_pubkey, data);
        require(success);
        return return_data;
    }

    function rotate_contract_pubkey(uint256 epoch, uint256 nonce)
        public
        check_cr(epoch)
        returns (bytes memory pubkey, bytes memory attestation)
    {
        pubkey = km().derive_pubkey(_input_enc_derive_path(nonce));
        attestation = attest_rotate(_onchain_rotate_pubkey_data(cr_epoch, nonce, pubkey));
    }

    function onchain_rotate_pubkey(bytes memory pubkey, bytes memory attestation)
        public
        verify_rotate(_onchain_rotate_pubkey_data(cr_epoch, pubkey_nonce, pubkey), attestation)
    {
        contract_pubkey = pubkey;
        pubkey_nonce = pubkey_nonce;
        bump_cr_epoch(cr_epoch);
    }

    // Typed attestation helper (can be autogenerated)
    struct _onchain_rotate_pubkey_data {
        uint256 cr_epoch;
        uint256 pubkey_nonce;
        bytes pubkey;
    }

    function attest_rotate(_onchain_rotate_pubkey_data memory user_data) private returns (bytes memory) {
        return offchain_attest(this.onchain_rotate_pubkey.selector, abi.encode(user_data));
    }

    modifier verify_rotate(_onchain_rotate_pubkey_data memory user_data, bytes memory attestation) {
        onchain_verify_fn(this.onchain_rotate_pubkey.selector, abi.encode(user_data), attestation);
        _;
    }

    function _input_enc_derive_path(uint256 nonce) private returns (bytes memory) {
        return versioned_derive_path(bytes.concat(input_enc_derivation_path_prefix, abi.encodePacked(nonce), "'"));
    }
}

/* Helper */
interface KeyManager {
    // function _seed() private returns (bytes memory); // See KeyManagerBase

    function derive_pubkey(bytes memory path) external returns (bytes memory privkey); // { return abi.encodePacked(BIP32.deriveChildKeyPairFromPath(_seed(), path)[1].key); }
    function derive_privkey(bytes memory path) external returns (bytes memory privkey); // { return abi.encodePacked(BIP32.deriveChildKeyPairFromPath(_seed(), path)[0].key); }

    function encrypt(bytes memory path, bytes memory plaintext) external returns (bytes memory ciphertext); // { return PKE.encrypt(this.derive_pubkey(path), Suave().localRandom(), plaintext); }
    function encrypt_to_pubkey(bytes memory pubkey, bytes memory plaintext)
        external
        returns (bytes memory ciphertext); // { return PKE.encrypt(pubkey, Suave().localRandom(), plaintext); }
    function decrypt(bytes memory path, bytes memory ciphertext) external returns (bytes memory plaintext); // { return PKE.decrypt(this.derive_privkey(path), ciphertext); }

    function refresh() external;
}
